# Generated by Django 6.0.5 on 2026-05-21 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='season',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='season',
            name='price_multiplier',
        ),
        migrations.RemoveField(
            model_name='season',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='suite',
            name='description',
        ),
        migrations.AddField(
            model_name='booking',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.suite'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suite',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
